# Generated by Django 5.2.1 on 2025-05-23 12:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(default='')),
                ('date_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='myfirstapp.user')),
            ],
        ),
    ]
