# Generated by Django 5.2.7 on 2025-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bus_number', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('bus_type', models.CharField(choices=[('AC', 'Air Conditioned'), ('NON_AC', 'Non-AC'), ('SLEEPER', 'Sleeper'), ('SEATER', 'Seater')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
